### ISSUE TITLE
Wrong filename in index.js

### ISSUE THREAD

**Issue by mr-wolf-rsh** [linchinghao/ok-enum#1]
Hey, great work here!

Just telling that you did a typo in this file:
https://github.com/linchinghao/ok-enum/blob/master/index.js

It says:
`require('./lib/enums.js')`

It should be as the filename:
`require('./lib/enum.js')`

**Comment by linqinghao** [comment]
Thanks @lone-wolf-96 , i have been fixed it and published a new package.
